# Generated by Django 5.0.6 on 2024-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pontoturistico_aprovado'),
        ('enderecos', '0002_rename_linha1_enderecos_logradouro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ManyToManyField(to='enderecos.enderecos'),
        ),
    ]
