# Generated by Django 5.0.6 on 2024-05-20 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0002_alter_avaliacoes_nota'),
        ('comentarios', '0002_rename_comentario_comentario_comentario'),
        ('core', '0006_alter_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='atracoes',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='comentario',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atracoes.atracao'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.avaliacoes'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.comentario'),
        ),
    ]
