# Generated by Django 5.0.6 on 2024-05-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecos',
            old_name='linha1',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='enderecos',
            old_name='linha2',
            new_name='rua_ou_bairro',
        ),
    ]
