# Generated by Django 5.0.6 on 2024-05-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_rename_linha1_enderecos_logradouro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enderecos',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='enderecos',
            name='longitude',
        ),
    ]
